### ISSUE TITLE
上拉加载能够当列表滑动到底部就自动开始加载么？

### ISSUE THREAD

**Issue by GeekZP** [wedxz/LNRefresh#11]
上拉加载能够当列表滑动到底部就自动开始加载么？现在滑动到底部还需要再往上拉一下

**Comment by vvusu** [comment]
LNRefreshFooter.m 方法中这个方法判断去掉，

            if (!self.scrollView.isDragging) {

然后修改     footer.animator.trigger  的值 为 0；

郑鹏 <notifications@github.com> 于2019年4月23日周二 上午11:16写道：
