### ISSUE TITLE
菊花刷新图标不见了

### ISSUE THREAD

**Issue by xiafb** [wedxz/LNRefresh#2]
🐹UITableView 这个Demo 中，点击 Change Animator 这个按钮，再取消选中，原先的菊花刷新图标不见了，需要重新运行才可以

**Comment by vvusu** [comment]
Demo 里面默认写死的是DIY 与 GIF 格式的切换，你换成NOR 就可以了，
[LNRefreshHandler changeAllHeaderAnimatorType:LNRefreshHeaderType_NOR bgImage:nil incremental:50];
