### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liwei5544** [wedxz/LNRefresh#4]
dyld: Library not loaded: @rpath/LNRefresh.framework/LNRefresh
  Referenced from: /Users/weili/Library/Developer/CoreSimulator/Devices/5F0DB1AC-8D56-44FB-8BF5-BAABD1C33186/data/Containers/Bundle/Application/21A26D55-53CA-4B22-9018-C6E52F5AC6F0/Refresh.app/Refresh
  Reason: no suitable image found.  Did find:
	/Users/weili/Library/Developer/CoreSimulator/Devices/5F0DB1AC-8D56-44FB-8BF5-BAABD1C33186/data/Containers/Bundle/Application/21A26D55-53CA-4B22-9018-C6E52F5AC6F0/Refresh.app/Frameworks/LNRefresh.framework/LNRefresh: required code signature missing for '/Users/weili/Library/Developer/CoreSimulator/Devices/5F0DB1AC-8D56-44FB-8BF5-BAABD1C33186/data/Containers/Bundle/Application/21A26D55-53CA-4B22-9018-C6E52F5AC6F0/Refresh.app/Frameworks/LNRefresh.framework/LNRefresh'

	/Users/weili/Library/Developer/CoreSimulator/Devices/5F0DB1AC-8D56-44FB-8BF5-BAABD1C33186/data/Containers/Bundle/Application/21A26D55-53CA-4B22-9018-C6E52F5AC6F0/Refresh.app/Frameworks/LNRefresh.framework/LNRefresh: required code signature missing for '/Users/weili/Library/Developer/CoreSimulator/Devices/5F0DB1AC-8D56-44FB-8BF5-BAABD1C33186/data/Containers/Bundle/Application/21A26D55-53CA-4B22-9018-C6E52F5AC6F0/Refresh.app/Frameworks/LNRefresh.framework/LNRefresh'

	/Users/weili/Library/Developer/CoreSimulator/Devices/5F0DB1AC-8D56-44FB-8BF5-BAABD1C33186/data/Containers/Bundle/Application/21A26D55-53CA-4B22-9018-C6E52F5AC6F0/Refresh.app/Frameworks/LNRefresh.framework/LNRefresh: required code signature missing for '/Users/weili/Library/Developer/CoreSimulator/Devices/5F0DB1AC-8D56-44FB-8BF5-BAABD1C33186/data/Containers/Bundle/Application/21A26D55-53CA-4B22-9018-C6E52F5AC6F0/Refresh.app/Frameworks/LNRefresh.framework/LNRefresh'

**Comment by vvusu** [comment]
建议运行，LNRefresh-Universal 这个Scheme  会打成 Framework，把 “LNRefresh.bundle“ 与 ”LNRefresh.framework“ 拖入工程里运行。建议拉最新代码，适配了iOS11。

**Comment by liwei5544** [comment]
pod 下载还是不行 必须手动导入么

**Comment by liwei5544** [comment]
手动导入报 
2017-09-30 11:27:17.826413+0800 Refresh[13640:1096400] -[UITableView addPullToRefresh:block:]: unrecognized selector sent to instance 0x7f80ce83c000
2017-09-30 11:27:17.830257+0800 Refresh[13640:1096400] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITableView addPullToRefresh:block:]: unrecognized selector sent to instance 0x7f80ce83c000'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b89a1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010ac7af41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b91a914 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKit                               0x000000010cc660bd -[UIResponder doesNotRecognizeSelector:] + 295
	4   CoreFoundation                      0x000000010b81d178 ___forwarding___ + 1432
	5   CoreFoundation                      0x000000010b81cb58 _CF_forwarding_prep_0 + 120
	6   Refresh                             0x000000010a2c405d _T07Refresh14ViewControllerC11viewDidLoadyyF + 877
	7   Refresh                             0x000000010a2c42a4 _T07Refresh14ViewControllerC11viewDidLoadyyFTo + 36
	8   UIKit                               0x000000010cbdbd51 -[UIViewController loadViewIfRequired] + 1235
	9   UIKit                               0x000000010cc234dc -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 68
	10  UIKit                               0x000000010cc23818 -[UINavigationController _startTransition:fromViewController:toViewController:] + 153
	11  UIKit                               0x000000010cc2492f -[UINavigationController _startDeferredTransitionIfNeeded:] + 841
	12  UIKit                               0x000000010cc25b90 -[UINavigationController __viewWillLayoutSubviews] + 115
	13  UIKit                               0x000000010ce7c2ae -[UILayoutContainerView layoutSubviews] + 231
	14  UIKit                               0x000000010cb0c551 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1331
	15  QuartzCore                          0x0000000112e214ba -[CALayer layoutSublayers] + 153
	16  QuartzCore                          0x0000000112e255a9 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	17  QuartzCore                          0x0000000112dae1cd _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 365
	18  QuartzCore                          0x0000000112dd9ae4 _ZN2CA11Transaction6commitEv + 500
	19  UIKit                               0x000000010ca59706 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 141
	20  CoreFoundation                      0x000000010b83d20c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	21  CoreFoundation                      0x000000010b821a3b __CFRunLoopDoBlocks + 203
	22  CoreFoundation                      0x000000010b821214 __CFRunLoopRun + 1300
	23  CoreFoundation                      0x000000010b820a89 CFRunLoopRunSpecific + 409
	24  GraphicsServices                    0x0000000112cfe9c6 GSEventRunModal + 62
	25  UIKit                               0x000000010ca3dd30 UIApplicationMain + 159
	26  Refresh                             0x000000010a2c6227 main + 55
	27  libdyld.dylib                       0x00000001105e0d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by vvusu** [comment]
要导入LNRefresh.bundle ，LNRefresh.framework 这两个。
