### ISSUE TITLE
collectionview设置了contentInset后，你的刷新控件不在自动下移啊

### ISSUE THREAD

**Issue by nenhall** [wedxz/LNRefresh#6]

**Comment by vvusu** [comment]
demo 中有collectionView.contentInset 有设置改变的。不知道你所说的问题具体是什么。

**Comment by nenhall** [comment]
@wedxz 你的tableView.y是从导航栏的下面开始，但我需要导航栏有穿透效果，所以我的tableview.y是从0开始，然后tableView.contentInset = UIEdgeInsetsMake(64, 0, 0, 0);让内容往下偏移，这个时候你的那个刷新控件不会跟着下移，你可以把你DemoVC.m中160行创建tableView的代码改成如下，最好把cell的背景色改成红色，好看一点：
```
self.tableView = [[UITableView alloc]initWithFrame:CGRectMake(0, 0, LNViewW, LNViewH) style:UITableViewStylePlain];
self.tableView.contentInset = UIEdgeInsetsMake(64, 0, 0, 0);
...后面的代码不变
```

**Comment by vvusu** [comment]
我写的这个是默认加上 UIEdgeInsetsMake 的距离的，你需要修改一下代码：


    header.frame = CGRectMake(self.contentOffset.x, -(header.animator.
incremental + self.contentInset.top), self.bounds.size.width, header.
animator.incremental);



改成这样：


    header.frame = CGRectMake(self.contentOffset.x, -(header.animator.
incremental), self.bounds.size.width, header.animator.incremental);



在 2018年1月19日 上午10:50，neghao <notifications@github.com>写道：

**Comment by nenhall** [comment]
@wedxz 嗯，现在可以了！之前就是没有点类扩展的`addPullToRefresh:`这个方法去看，其它的类里面都看，改了，都不行！原来是在这里。
