### ISSUE TITLE
Xcode10编译的时候报错info.plist

### ISSUE THREAD

**Issue by zjinhu** [wedxz/LNRefresh#8]
Xcode10编译报错

**Comment by zjinhu** [comment]
pod的代码目录里边多了一个info.plist文件，pod进来xcode10编译会提示报错，望修复

**Comment by zjinhu** [comment]
好像是资源文件里边多的

**Comment by kaelinda** [comment]
Xcode 10  对文件的编译 要求严格了，不允许重名的

**Comment by pcjbird** [comment]
感觉作者不打算维护这个库了～～～

**Comment by pcjbird** [comment]
cocoapods 没提交？

**Comment by wedxz** [comment]
还没，正在弄

**Comment by vvusu** [comment]
已更新 pod 1.0.4 版本，或者直接打包成Framework 使用
