### ISSUE TITLE
resource 文件内关联的本地文件获取不到

### ISSUE THREAD

**Issue by kaelinda** [wedxz/LNRefresh#9]
resource 文件内关联的本地文件获取不到
    NSString *filePath = [[NSBundle mainBundle] pathForResource:@"LNRefresh.bundle/lnrefresh" ofType:@"json"];
filePath 是nil,下拉图片也获取不到

**Comment by zjinhu** [comment]
拷他的代码直接做一个自己的私有库吧

**Comment by kaelinda** [comment]
你这个方法好用，但是...这样感觉不太合适哈哈哈

**Comment by vvusu** [comment]
已更新 pod 1.0.4版本，或者直接打包成Framework
